In [42]:
import pandas as pd
import numpy as np


s1 = 'data.csv'

In [43]:
df = pd.read_csv(s1, header=None, delim_whitespace=True)

In [44]:
df
#print(df.shape[0])

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,MX000017004195504TMAX,310,310,310,320,330,320,320,330,330,...,330,330,330,330,330,330,340,330,320,-9999
1,MX000017004195504TMIN,150,150,160,150,160,160,160,160,160,...,170,170,170,180,190,190,170,180,160,-9999
2,MX000017004195504PRCP,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,-9999
3,MX000017004195505TMAX,310,310,310,300,300,300,310,310,310,...,330,340,350,330,310,310,320,310,300,290
4,MX000017004195505TMIN,200,160,160,150,150,150,160,160,170,...,170,190,190,190,180,160,150,170,150,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1709,MX000017004201103TMIN,-9999,-9999,-9999,-9999,148,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,162,-9999,-9999,-9999,-9999,170
1710,MX000017004201103PRCP,0,-9999,0,0,0,-9999,0,0,0,...,0,-9999,0,-9999,0,-9999,-9999,0,-9999,0
1711,MX000017004201104TMAX,-9999,350,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
1712,MX000017004201104TMIN,-9999,168,-9999,-9999,-9999,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
1713,MX000017004201104PRCP,0,0,-9999,-9999,0,0,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999

In [45]:
# extracting date and type of measurement from 1 collumn 
id_l = []
rok_l = []
mies_l =[]
nazw_zmienn_l =[]
for i in range(df.shape[0]):
    id_l.append(df[0][i][0:11])
    rok_l.append(df[0][i][11:15])
    mies_l.append(df[0][i][15:17])
    nazw_zmienn_l.append(df[0][i][17:21])

    

series_1 = pd.Series(id_l)
series_2 = pd.Series(rok_l)
series_3 = pd.Series(mies_l)
series_4 = pd.Series(nazw_zmienn_l)

df.drop(0, axis='columns', inplace=True)

#  creating and inserting new collumns containing newly obtained informations 

df.insert(0, 'Id', series_1)
df.insert(1, 'rok', series_2)
df.insert(2, 'miesiac', series_3)
df.insert(3, 'element', series_4)

df

,Id,rok,miesiac,element,1,2,3,4,5,6,...,22,23,24,25,26,27,28,29,30,31
0,MX000017004,1955,04,TMAX,310,310,310,320,330,320,...,330,330,330,330,330,330,340,330,320,-9999
1,MX000017004,1955,04,TMIN,150,150,160,150,160,160,...,170,170,170,180,190,190,170,180,160,-9999
2,MX000017004,1955,04,PRCP,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,-9999
3,MX000017004,1955,05,TMAX,310,310,310,300,300,300,...,330,340,350,330,310,310,320,310,300,290
4,MX000017004,1955,05,TMIN,200,160,160,150,150,150,...,170,190,190,190,180,160,150,170,150,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1709,MX000017004,2011,03,TMIN,-9999,-9999,-9999,-9999,148,-9999,...,-9999,-9999,-9999,-9999,162,-9999,-9999,-9999,-9999,170
1710,MX000017004,2011,03,PRCP,0,-9999,0,0,0,-9999,...,0,-9999,0,-9999,0,-9999,-9999,0,-9999,0
1711,MX000017004,2011,04,TMAX,-9999,350,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
1712,MX000017004,2011,04,TMIN,-9999,168,-9999,-9999,-9999,-9999,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999
1713,MX000017004,2011,04,PRCP,0,0,-9999,-9999,0,0,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999

In [46]:
ser_vb = df['rok']+"-"+df['miesiac']
df.drop("rok", axis='columns', inplace=True)
df.drop("miesiac", axis='columns', inplace=True)
df.insert(1, 'data', ser_vb)

df2 = df.melt(id_vars = ["Id","data","element"])

In [47]:
df2['variable'] = df2['variable'].astype(str)
df2ser_vb = df2['data']+"-"+df2['variable']
df2.drop("variable", axis='columns', inplace=True)
df2.drop("data", axis='columns', inplace=True)
df2.insert(1, 'data', df2ser_vb)
df2.sort_index(axis=0,ascending=True)
df2 = df2.sort_values(by="data")

df2.reset_index(inplace = True, drop = True)

df2.head(15)

             Id        data element value
0   MX000017004   1955-04-1    TMAX   310
1   MX000017004   1955-04-1    TMIN   150
2   MX000017004   1955-04-1    PRCP     0
3   MX000017004  1955-04-10    PRCP     0
4   MX000017004  1955-04-10    TMIN   170
5   MX000017004  1955-04-10    TMAX   330
6   MX000017004  1955-04-11    TMAX   330
7   MX000017004  1955-04-11    PRCP     0
8   MX000017004  1955-04-11    TMIN   170
9   MX000017004  1955-04-12    TMIN   160
10  MX000017004  1955-04-12    PRCP     0
11  MX000017004  1955-04-12    TMAX   320
12  MX000017004  1955-04-13    PRCP     0
13  MX000017004  1955-04-13    TMIN   160
14  MX000017004  1955-04-13    TMAX   310

In [48]:
df2.to_csv('data_tidy.csv',index=True)